config/routes.rb
Rails.application.routes.draw do
  
  # トップページ
  root to: 'toppages#index';

  # /favorites へのアクセスでお気に入り一覧を表示するようにする
  get 'favorites', to: 'toppages#favorites';
  
  
  # ログイン周り
  get    'login' , to: 'sessions#new';
  post   'login' , to: 'sessions#create';
  delete 'logout', to: 'sessions#destroy';


  # ユーザ周り
  
  # /signup へのアクセスでuserが新規作成できるようにする
  get 'signup', to: 'users#new';
  
  # edit, update, destroyは無し
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
    end
    collection do
      #get :search
    end
  end


  # 投稿周り
  resources :microposts, only: [:create, :destroy] do
    # お気に入り周り
    resource :favorites, only: [:create, :destroy];
  end
  
  # フォロー周り
  resources :relationships, only: [:create, :destroy];
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user;
  belongs_to :micropost;

  validates :user_id, presence: true;
  validates :micropost_id, presence: true;
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  # お気に入りの操作は必ずログイン済み前提とする
  before_action :require_user_logged_in;
  
  def create
    @micropost = Micropost.find(params[:micropost_id]);
    current_user.favorite(@micropost);
  end

  def destroy
    @micropost = Micropost.find(params[:micropost_id]);
    current_user.unfavorite(@micropost);
  end
  
end

app/views/favorites/_favorite.html.erb
<%# 対象の記事をお気に入りにするリンクを作る %>
<%# @params micropost: 対象の記事 %>

<%#
    MEMO: Ajaxでのリンクを使用するためにremote: trueを使用
    参考: https://railsguides.jp/working_with_javascript_in_rails.html
%>
<%= link_to micropost_favorites_path(micropost), method: :post, remote: true, class: 'btn btn-default btn-xs' do %>
  <span class="glyphicon glyphicon-heart"></span>
<% end %>

app/views/favorites/_favorite_form.html.erb
<%#
  お気に入りにする・しないボタンを表示
  @param :micropost
%>

<span id="favorite_form-<%= micropost.id %>">
  <% if current_user.favorite?(micropost) %>
    <%# お気に入り中 %>
    <%= render "favorites/unfavorite", micropost: micropost %>
  <% else %>
    <%# お気に入りしてない %>
    <%= render "favorites/favorite", micropost: micropost %>
  <% end %>
</span>

app/views/favorites/_unfavorite.html.erb
<%# 対象の記事をお気に入りから外すリンクを作る %>
<%# @params micropost: 対象の記事 %>

<%#
    MEMO: Ajaxでのリンクを使用するためにremote: trueを使用
    参考: https://railsguides.jp/working_with_javascript_in_rails.html
%>
<%= link_to micropost_favorites_path(micropost), method: :delete, remote: true, class: 'btn btn-danger btn-xs' do %>
  <span class="glyphicon glyphicon-heart"></span>
<% end %>

app/views/favorites/create.js.erb
<%# 表示されている対象の記事のリンクを切り替える %>
$('#favorite_form-<%= @micropost.id %>').html('<%=j render 'favorites/unfavorite', micropost: @micropost %>');

app/views/favorites/destroy.js.erb
<%# 表示されている対象の記事のリンクを切り替える %>
$('#favorite_form-<%= @micropost.id %>').html('<%=j render 'favorites/favorite', micropost: @micropost %>');