config/routes.rb
Rails.application.routes.draw do
  
  # トップページ
  root to: 'toppages#index';

  # /favorites へのアクセスでお気に入り一覧を表示するようにする
  get 'favorites', to: 'toppages#favorites';
  
  
  # ログイン周り
  get    'login' , to: 'sessions#new';
  post   'login' , to: 'sessions#create';
  delete 'logout', to: 'sessions#destroy';


  # ユーザ周り
  
  # /signup へのアクセスでuserが新規作成できるようにする
  get 'signup', to: 'users#new';
  
  # edit, update, destroyは無し
  resources :users, only: [:index, :show, :new, :create] do
    member do
      get :followings
      get :followers
    end
    collection do
      #get :search
    end
  end


  # 投稿周り
  resources :microposts, only: [:create, :destroy] do
    # お気に入り周り
    resource :favorites, only: [:create, :destroy];
  end
  
  # フォロー周り
  resources :relationships, only: [:create, :destroy];
  
end

app/models/user.rb
class User < ApplicationRecord
  
  before_save { self.email.downcase! };
  
  validates :name, presence: true, length: { maximum: 50 };
  
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false };
  
  has_secure_password;
  
  
  has_many :microposts;
  
  has_many :favorites, dependent: :destroy;
  has_many :favorite_microposts, through: :favorites, source: :micropost;
  
  # お気に入りにする
  # @param micropost: 対象の投稿
  def favorite(micropost)
    self.favorites.find_or_create_by(micropost_id: micropost.id);
  end
  
  # お気に入りを外す
  # @param micropost: 対象の投稿
  def unfavorite(micropost)
    favorite = self.favorites.find_by(micropost_id: micropost.id);
    favorite.destroy if favorite;
  end
  
  # お気に入りにしているか確認する
  # @param micropost: 対象のmicropost
  # @return: お気に入りにしていればtrue
  def favorite?(micropost)
    return self.favorite_microposts.include?(micropost);
  end
  
  
  # フォローしているユーザ
  # relationships（Relationshipモデル群内のuser）を経由してfollowを取得するfollowingsを定義
  has_many :relationships;
  has_many :followings, through: :relationships, source: :follow;
  
  # フォローしてきているユーザ
  # reverses_of_relationship（Relationshipモデル群内のfollow）を経由してuserを取得するfollowersを定義
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id';
  has_many :followers, through: :reverses_of_relationship, source: :user;
  

  # フォローする
  # @param other_user: 対象のユーザ
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id);
    end
  end
  
  # フォローを外す
  # @param other_user: 対象のユーザ
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id);
    relationship.destroy if relationship;
  end
  
  # フォローしているか確認する
  # @param other_user: 対象のユーザ
  # @return: フォローしていればtrue
  def following?(other_user)
    return self.followings.include?(other_user);
  end
  
  
  # ユーザ自身とユーザがフォローしているユーザの投稿を取得する
  # @return: 該当する投稿群
  def feed_microposts
    return Micropost.where(user_id: self.following_ids + [self.id]);
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # ログイン時のみ表示するページを指定
  before_action :require_user_logged_in, only: [:index, :show, :followings, :followers];
  
  def index
    @users = User.all.page(params[:page]);
  end

  def show
    @user = User.find(params[:id]);
    @microposts = @user.microposts.order('created_at DESC').page(params[:page]);
    counts(@user);
  end

  def new
    @user = User.new;
  end

  def create
    @user = User.new(user_params);
    
    if @user.save
      # ユーザ作成と同時にログイン状態にする
      session[:user_id] = @user.id;
      
      flash[:success] = 'ユーザを登録しました。';
      redirect_to @user;
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。';
      render :new;
    end
  end
  
  
  def followings
    @user = User.find(params[:id]);
    @followings = @user.followings.page(params[:page]);
    counts(@user);
  end
  
  def followers
    @user = User.find(params[:id]);
    @followers = @user.followers.page(params[:page]);
    counts(@user);
  end

  
  private
  # 以下privateメンバ
  
  # Strong Paramter
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation);
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
  # Gravatar(https://ja.gravatar.com/)に登録されている画像のurlを取得する
  # @param user: 対象のユーザのモデルインスタンス
  # @param options: Gravatarの仕様に沿って追加するオプションの内容
  #                 size: URL?s=[size] サイズ指定、1～2048pxまで
  def gravatar_url(user, options = { size: 80 })
    # 小文字のみメアドをMD5でハッシュに変換
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase);
    size = options[:size];
    return "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}";
  end
end

app/views/users/_users.html.erb
<%# @param users: リスト表示するユーザのモデルインスタンス %>

<% if users.any? %>

  <ul class="media-list">
    <% users.each do |user| %>
      <li class="media">
        <div class="media-left">
          <img class="media-object img-rounded" src="<%= gravatar_url(user, {size: 50 }) %>" alt="<%= user.name %> icon">
        </div>
        <div class="media-body">
          <div>
            <%= user.name %>
          </div>
          <div>
            <p><%= link_to 'View profile', user_path(user) %></p>
          </div>
        </div>
      </li>
    <% end %>
    
    <%= paginate users %>
  </ul>
  
<% else %>
  <%# 該当ユーザなし %>
<% end %>

app/views/users/followers.html.erb
<div class="row">
  
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="<%= @user.name %> image">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>">
        <%= link_to user_path(@user) do %>
          Microposts <span class="badge"><%= @count_microposts %></span>
        <% end %>
      </li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>">
        <%= link_to followings_user_path(@user) do %>
          Followings <span class="badge"><%= @count_followings %></span>
        <% end %>
      </li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>">
        <%= link_to followers_user_path(@user) do %>
          Followers <span class="badge"><%= @count_followers %></span>
        <% end %>
      </li>
    </ul>
    <%= render 'users', users: @followers %>
  </div>
  
</div>

app/views/users/followings.html.erb
<div class="row">
  
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="<%= @user.name %> image">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(user_path(@user)) %>">
        <%= link_to user_path(@user) do %>
          Microposts <span class="badge"><%= @count_microposts %></span>
        <% end %>
      </li>
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>">
        <%= link_to followings_user_path(@user) do %>
          Followings <span class="badge"><%= @count_followings %></span>
        <% end %>
      </li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>">
        <%= link_to followers_user_path(@user) do %>
          Followers <span class="badge"><%= @count_followers %></span>
        <% end %>
      </li>
    </ul>
    <%= render 'users', users: @followings %>
  </div>
  
</div>

app/views/users/index.html.erb
<%= render 'users', users: @users %>

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-md-offset-3 col-md-6">
    
    <%= form_for(@user) do |f| %>
      
      <%# エラーメッセージをレンダリング %>
      <%# MEMO:f.objectには対象のモデルオブジェクト（@user）が入ってる %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <%= f.submit 'Sign Up', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  
  <aside class="col-xs-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title"><%= @user.name %></h3>
      </div>
      <div class="panel-body">
        <img class="img-rounded img-responsive" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="<%= @user.name %> image">
      </div>
    </div>
  </aside>
  
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(@user) %>">
        <%= link_to user_path(@user) do %>
          Microposts <span class="badge"><%= @count_microposts %></span>
        <% end %>
      </li>
      <li><a href="#">Followings</a></li>
      <li><a href="#">Folloers</a></li>
    </ul>
    <%= render 'microposts/microposts', microposts: @microposts %>
  </div>
</div>